name: Sync content to Azure Blob

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "production" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to Azure Blob
        uses: azure/cli@v2
        with:
            inlineScript: |
                # Upload README.md
                az storage blob upload-batch \
                    --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
                    --destination $CONTAINER \
                    --source . \
                    --pattern "README.md" \
                    --auth-mode login
                
                # Upload content files
                az storage blob upload-batch \
                    --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
                    --destination $CONTAINER \
                    --source app/content \
                    --destination-path content \
                    --auth-mode login
                
                # Upload text files
                az storage blob upload-batch \
                    --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
                    --destination $CONTAINER \
                    --source text-files \
                    --destination-path text-files \
                    --auth-mode login
        env:
          CONTAINER: container-davdevs

